// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afeyvmnztzlygydykppn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZXl2bW56dHpseWd5ZHlrcHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2MDI0MzAsImV4cCI6MjA4MDE3ODQzMH0.yswIiJjwSQOaCTZCO8FUcJFAKLIGeI_tjCLLiBtnVgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});